# Generated by Django 5.2.6 on 2025-09-24 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_de_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
    ]
