# Generated by Django 5.2.6 on 2025-09-29 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_de_entrega', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='M', max_length=1)),
                ('fileira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos_app.fileira')),
                ('responsaveis', models.ManyToManyField(related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
