# Generated by Django 5.2.6 on 2025-09-28 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarefas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
    ]
